site_name: TaskMaster

repo_name: "TaskMaster"
repo_url: "https://github.com/DigogSXD/TaskMaster"

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: '#3dafe5'
      accent: '#3dafe5'
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: '#3dafe5'
      accent: '#3dafe5'


  font:
    text: "Montserrat"
    code: "sans-serif"

nav:
  - Introdução: index.md
  - Funcionalidades:
    - Tela de Login: funcionalidades/telalogin.md
  - planejamento: planejamento/ferramentas.md
  







extra_css:
  - custom.css
