site_name: TaskMaster

repo_name: "TaskMaster"
repo_url: "https://github.com/DigogSXD/TaskMaster"

theme:
  name: material
  language: pt-BR
  features:
    - navigation.instant
    - navigation.section
    - navigation.path
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
  logo: "logo/Logo_TM.png"  
  palette:
    - scheme: default
      primary: yellow
      toggle:
        icon: material/weather-night
        name: Modo noturno
    - scheme: slate
      primary: yellow
      toggle:
        icon: material/weather-sunny
        name: Modo claro

  font:
    text: "Montserrat"
    code: "sans-serif"

nav:
  - Introdução: index.md
  - Funcionalidades:
    - Tela de Login: funcionalidades/telalogin.md
  - Planejamento: 
    - Ferramentas: planejamento/ferramentas.md

extra_css:
  - custom.css
